### ISSUE TITLE
enhancement: right-click paste; and perhaps paste+go

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/sn_browser#1241] opened 2020-04-04 16:04 UTC
safe-browser-v0.17.0-alpha.11-linux-x64.AppImage
is not providing a right-click option on the url bar.

I was expecting options for paste at least but would be good to see the usual run of [Undo; Cut; Copy; Paste; Paste & Go; Delete; Select All] that is usual for text input environments.

**Comment by S-Coyle** [comment] 2020-10-21 15:52
Duplicate of #849

**Closed by S-Coyle** 2020-10-21 15:52 UTC
