### ISSUE TITLE
Problems with 'Reconnect Now'

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/sn_browser#457] opened 2018-12-07 12:35 UTC
This issue seems similar to PR #319, however there are some differences
- as mentioned in 319, it works with auth page, but it shows `Unable to navigate to site. Will automatically reload when network is connected...` message when I open a new tab to access a webpage.
- the new issue is intermittent and this also happens when I click `reconnect now`
- this time the reconnecting spinner spins infinitely
- and the browser becomes unresponsive, such as logout button doesn't work, unable to switch tabs, needs about 5 clicks to switch next tab. STR: try opening new tab and try to access some link, while it is loading click auth page tab

Note: I got this issue on Windows with prod version

**Comment by bochaco** [comment] 2018-12-07 14:30
I'm also able to reproduce most of what you describe with the exception of the browser being unresponsive, that doesn't happen to me (on Linux), the reconnect works fine from the authenticator. The authenticator is able to reconnect successfully, but new tabs cannot connect, although existing tabs with already opened apps are able to reconnect afterwards as well, so it seems the problem is only with new tabs.
A secondary issue is that the warning message on the top which says `reconnecting now` doesn't go away automatically, even after I clicked to reconnect in the authenticator.

**Comment by hunterlester** [comment] 2019-01-09 19:02
Blocking issue. Current state:

Got my hands on a Mac for testing purposes.
There are two primary issues:
1. When loading a site just before network disconnect is observed, then opening a blank tab, the loading tab triggers a `did-fail-load` webview event. Not able to reproduce this on Windows. This is an easy problem as I have to consider that either `webFetch` can error or Chromium webview can error, so I just have to handle both of those cases. Leading to the next problem.
2. I'm able to handle both Chromium and `webFetch` errors and observe a tab begin to reload as expected, HOWEVER, if that tab is not currently active, then the page will render blank, if it is active it will render the page as expected.

See latest commit.

**Comment by hunterlester** [comment] 2019-01-10 20:14
#410 should be completed in order to resolve remaining OSX-specific issues.

**Comment by S-Coyle** [comment] 2020-10-21 14:09
Closing legacy issue

**Closed by S-Coyle** 2020-10-21 14:09 UTC
Labels: blocked, bug
